Add prefix to local functions
tjosk reports:

"seriously, you wrote it as a lib, but are using too generic function names
 (and i dont even want to think if there are global variables/defs that might
 conflict too). some time ago i've reported that libxmp defines 'inflate'
 function which is also used in libz (my quick fix was to change all
 occurances of 'inflate' to 'xmp_inflate'). now there is another:

 /1/_src/oscp/local/usr/local/lib/libxmp.a(mix_paula.o): In function `paula_init':
 mix_paula.c:(.text.paula_init+0x0): multiple definition of `paula_init'
 /1/_src/oscp/local/usr/local/lib/libsc68.a(paulaemul.o):paulaemul.c:(.text.paula_init+0x0): first defined here
 collect2: error: ld returned 1 exit status

 both things can be simply renamed in libxmp without breaking anything. please do!"

 Add libxmp_ prefix to some local functions to prevent namespace clashes when
 statically linking the library.

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>