Rename clock function to prevent conflict in OpenBSD
Frederic Cambus reports:

"When trying to compile libxmp on my system (OpenBSD) using the latest
 release tarball (4.4.0), I'm getting the following error:

 src/mix_paula.c:67: error: conflicting types for 'clock'
 /usr/include/time.h:127: error: previous declaration of 'clock' was here
 gmake: *** [Makefile:66: src/mix_paula.lo] Error 1
 Renaming clock to something like paula_clock solves the issue."

Renamed clock() to do_clock().

Signed-off-by: Claudio Matsuoka <cmatsuoka@gmail.com>